{
 "title": "OTEL Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Application Uptime Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(laratel_application_uptime_seconds_sum{service_name=\"otel_service_name\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests & Latency Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(laratel_http_request_total{service_name=\"otel_service_name\"})",
     "legendFormat": "Total Request"
    }
   ]
  },
  {
   "title": "Total HTTP Request by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(http_method) (laratel_http_status_code_total{service_name=\"otel_service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Status by Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(http_method, http_status_code, http_route) (laratel_http_status_code_total{service_name=\"otel_service_name\"})",
     "legendFormat": "[{{http_method}}] [{{http_status_code}}] {{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laratel_http_request_latency_seconds_sum{service_name=\"otel_service_name\"}",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Request Size by Routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (http_route) (\n  laratel_http_request_size_bytes_sum{service_name=\"otel_service_name\"}\n)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Response Size by Routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (http_route) (\n  laratel_http_response_size_bytes_sum{service_name=\"otel_service_name\"}\n)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Request in Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (http_route) (\n  laratel_http_requests_in_progress_sum{service_name=\"otel_service_name\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "laratel_http_failed_requests_total{service_name=\"otel_service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DB Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Total DB Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(laratel_db_query_total{service_name=\"otel_service_name\"})",
     "legendFormat": "Total DB Queries"
    }
   ]
  },
  {
   "title": "DB Query Latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(query) (laratel_db_query_latency_seconds_sum{service_name=\"otel_service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trace Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Application Trace by Jaeger",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "service": "otel_service_name" }
   ]
  },
  { "title": "System Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Average System Disk State",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(laratel_system_disk_total_bytes_sum{service_name=\"otel_service_name\"})",
     "legendFormat": "Total Disk Space"
    },
    {
     "expr": "sum(laratel_system_disk_usage_bytes_sum{service_name=\"otel_service_name\"})",
     "legendFormat": "Total Disk Usage"
    },
    {
     "expr": "sum(laratel_system_disk_free_bytes_sum{service_name=\"otel_service_name\"})",
     "legendFormat": "Total Disk Free"
    }
   ]
  },
  {
   "title": "CPU Usage Last 24 Hrs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (\n  rate(laratel_system_cpu_time_seconds_total{service_name=\"otel_service_name\"}[24h])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(type) (laratel_system_memory_usage_bytes_sum{service_name=\"otel_service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "I/O Network by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "laratel_system_network_io_bytes_total{service_name=\"otel_service_name\"}",
     "legendFormat": "{{host}} ({{interface}})"
    }
   ]
  },
  {
   "title": "Inbound Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "laratel_network_inbound_bytes_sum{service_name=\"otel_service_name\"}",
     "legendFormat": "{{host}} ({{interface}})"
    }
   ]
  },
  {
   "title": "Outbound Network by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "laratel_network_outbound_bytes_sum{service_name=\"otel_service_name\"}",
     "legendFormat": "{{host}} ({{interface}})"
    }
   ]
  },
  {
   "title": "Total Network Drop by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "laratel_system_network_dropped_total{service_name=\"otel_service_name\"}",
     "legendFormat": "{{host}} ({{interface}})"
    }
   ]
  },
  {
   "title": "Network Error by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "laratel_system_network_errors_total{service_name=\"otel_service_name\"}",
     "legendFormat": "{{host}} ({{interface}})"
    }
   ]
  },
  {
   "title": "Active Network Connection by Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "rate(laratel_active_network_connections_sum{service_name=\"otel_service_name\"}[24h])",
     "legendFormat": "{{host}} - {{state}}"
    }
   ]
  }
 ]
}