global:
  scrape_interval: 15s  # Default scrape interval
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from the OpenTelemetry Collector
  - job_name: 'otel-collector'
    scrape_interval: 5s  # More frequent scraping for OTLP metrics
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otel-collector:8889'] # Uses container name within Docker network
